### ISSUE TITLE
automatically get number of chapters

### ISSUE THREAD

**Issue by elbotho** [elbotho/pleasure-in-scarcity#1]
@danielparnitzke for now just replace the 3 with 100 and you are good to go 👍 
https://github.com/elbotho/pleasure-in-scarcity/blob/fde524d8f02c3b1a287982af3bd858e8b81e3e65/src/components/app.js#L74

**Comment by danielparnitzke** [comment]
increasing the number does not add more chapters. May this be a cache problem?
